baseURL = 'https://www.grayhatnews.com/'
languageCode = 'en-us'
title = 'Gray Hat News'
theme = 'pehtheme-hugo'
paginate = '6'
summaryLength = '20'
googleAnalytics = 'G-8N89EQ5F48'
disqusShortname = 'tonybalvida'
enableRobotsTXT = true

[params]
description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
mainSections = 'posts'

[author]
name = 'GrayHat Media'
bio = 'A writer about all innovative things in the service, residential, and tech sector.'
avatar = '/images/nasa-astronaut-unsplash.jpg'
twitter = 'https://twitter.com/butterreader'

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"
lastmod = true  # Automatically update last modification date

[securityHeaders]
ContentSecurityPolicy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 15
[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[module]
hugoVersion = { extended = false, min = "0.116.0" }
mounts = [{ source = 'assets', target = 'static' }]
